name: Copy

on:
  schedule:
    Monday, Tuesday, Thursday, and Friday every 1 hour from 5:00 PM to 8:00 PM CET
    - cron: '0 17-20 * * 1,2,3,4,5'

    On every day every 4 hours
    - cron: '30 */4 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The first job in this workflow is named build-on-ubuntu
    build-and-run:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        
        - name: step 1 - Checkout the main GitHub branch
          uses: actions/checkout@v2 

        - name: Step 2 - let's curl!
          run: curl -v https://sofafeed.macadmins.io/v1/macos_data_feed.json --create-dirs --output v1/macos_data_feed.json

        - name: Step 3 - Commit and push if changes are detected
          run: |
            timestamp=$(date +'%Y-%m-%d %H:%M:%S')
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add v1/*.json
            git commit -m "Update SOFA data - $timestamp" -a || exit 0
            git push
